### ISSUE TITLE
Issue rendering XML after git pull

### ISSUE THREAD

**Issue by TehPeGaSuS** [meain/gh-issues-to-rss#10]
I've `git pull` and then `go clean` and `go build`. am I missing any other steps?

Because I'm seeing this on the RSS page:
![](https://imgur.com/Sv0pIM0.png)

I can see the same exact issue on the demo server.

Example url: [https://gh-issues-to-rss.fly.dev/anope/anope](https://gh-issues-to-rss.fly.dev/anope/anope)

**Comment by TehPeGaSuS** [comment]
After a `go clean` and `go build` all seems to work but the demo server still has the issue.
May be cache related?

**Comment by meain** [comment]
Looks like an incident in fly.io (ref: https://status.flyio.net/). Should ideally go away once that is resolved.

**Comment by meain** [comment]
Looked a bit more into it. I had deleted ipv4 address from fly.io as they started charging for it, but looks like the world is not ready for it yet. I've added it back for now(shared) and things should now work.
