### ISSUE TITLE
Invalid URL thrown when using an URL with trailing slash

### ISSUE THREAD

**Issue by TehPeGaSuS** [meain/gh-issues-to-rss#12]
The server will throw an `Invalid URL` if you use `https://github.com/meain/gh-issues-to-rss/` instead of `https://github.com/meain/gh-issues-to-rss`.
The application could probably remove the trailing slash on its own?

**Comment by meain** [comment]
Should be fixed now

**Comment by TehPeGaSuS** [comment]
The demo server seems to not be up-to-date with the git repo.

On [my instance](https://rssgen.0bin.xyz/) (just updated), if you try to generate the URL from `https://github.com/meain/gh-issues-to-rss/` there's no error but there's also no URL generated.

Using `https://github.com/meain/gh-issues-to-rss` works as expected.

**Comment by meain** [comment]
Ahh, I didn't update the UI, only did it on the server side. Let me fix that.

**Comment by meain** [comment]
Fixed in 31847a1 and deployed!
