### ISSUE TITLE
How to change listening port?

### ISSUE THREAD

**Issue by TehPeGaSuS** [meain/gh-issues-to-rss#6]
I can't seem to find a way to specify the listening port of the server.

Is that possible, since I already have port `8080` taken.

Cheers

**Comment by meain** [comment]
This might not be the ideal interface, but you can set the [`PORT`](https://github.com/meain/gh-issues-to-rss/blob/175f62d68a68c6c7bc7e2d5943e4e43005cb08a0/main.go#L167) env variable before calling the binary.

```sh
PORT=8787 gh-issues-to-rss --server
```

**Comment by TehPeGaSuS** [comment]
That works for me. :D

It'd be nice to have something like `gh-issues-to-rss --server --port 8787` instead, probably.

**Comment by meain** [comment]
Yeah I agree, `--port` would be better. I might get around to it over the weekend. Do feel free to submit a PR if you are interested.

**Comment by TehPeGaSuS** [comment]
I'd love to, but unfortunately me and coding don't go along very well :sweat_smile:

**Comment by meain** [comment]
@TehPeGaSuS this should now be fixed
