### ISSUE TITLE
Not understanding `We invalidate internal cache only every 12 hours`

### ISSUE THREAD

**Issue by TehPeGaSuS** [meain/gh-issues-to-rss#7]
Does `We invalidate internal cache only every 12 hours` means that the RSS feeds will only be updated every 12h?

If so, can we invalidate the cache manually more often?

Cheers

**Comment by meain** [comment]
> Does We invalidate internal cache only every 12 hours means that the RSS feeds will only be updated every 12h?

[Yup](https://github.com/meain/gh-issues-to-rss/blob/175f62d68a68c6c7bc7e2d5943e4e43005cb08a0/core.go#L137), you are right. We save the GH response for 12 hours and only fetch again after 12 hours. This was a quick hack to prevent GitHub from rate limiting. It does not have to be this aggressive, but it was mostly for my personal use and this was working pretty well.

*This would be another thing which could benefit from a flag to configure, something like `--cache-timeout <interval>`. It is unfortunately [fixed](https://github.com/meain/gh-issues-to-rss/blob/175f62d68a68c6c7bc7e2d5943e4e43005cb08a0/core.go#L64) as of now*

> If so, can we invalidate the cache manually more often?

Let me see if I can get around to adding a flag over the weekend, but one quick hack would be to delete the cache files located at `/tmp/gh-issues-to-rss-cache` with a cron job or something. Super hacky, but it would work.

**Comment by TehPeGaSuS** [comment]
I know that GitHub has rate limits, but I'd use this to follow several GitHub repos, so having less cache time would be greatly appreciated.

Accordig to [this docs](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28), when using personal access token, we have way higher rate limits.

Here's some ideas:
- It would it be worthy to have a way to add/specify a personal access token, via some flag like `--access-token <TOKEN>`.
- 1h caching would, probably, be enough for most of the users. If we specify a token, then the standard rate limit would be ignored.

I know that this would mean re-writting stuff, but would be a great improvement.

Cheers!

**Comment by meain** [comment]
> I know that GitHub has rate limits, but I'd use this to follow several GitHub repos, so having less cache time would be greatly appreciated.

FYI, the cache is per repo.

> Accordig to [this docs](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28), when using personal access token, we have way higher rate limits.

Yup, you are right. I just never got around to do it as this was mostly a personal project and I didn't really have use for it. Now sound a good time as any to implement it.

**Comment by meain** [comment]
@TehPeGaSuS this should now be fixed
